### PR TITLE
Updating euro mean parity.

### PR DESCRIPTION
**Pull request by LeonaLj**
Corrected official HRK to EUR exchange rate in the process of croatian adoption of the euro. 
https://euro.hnb.hr/-/hi11072020_vujcic_n1
https://www.tportal.hr/biznis/clanak/vujcic-otkrio-po-kojem-tecaju-cemo-mijenjati-kune-u-eure-ali-i-porucio-nije-dobro-drzati-gotovinu-kod-kuce-rizik-je-od-pljacke-foto-20210913/print

### CODE REVIEW

**Comment by darko55555** [comment]
@jtomic-croz did anyone have time to take a look ?

**Comment by jtomic-croz** [comment]
@darko55555 took a look at it now, I'merge it and release a new version today :)

**Comment by darko55555** [comment]
@jtomic-croz Awesome 🥳

**Comment by jtomic-croz** [comment]
@darko55555 @LeonaLj version 1.0.4 which includes new exchange rate is released 
https://www.npmjs.com/package/@croz/hrk2eur/v/1.0.4
https://unpkg.com/@croz/hrk2eur@1.0.4/dist/umd/main.js

**Comment by darko55555** [comment]
@jtomic-croz @LeonaLj 🚀

**Comment by LeonaLj** [comment]
@jtomic-croz 🥳

**Pull request merged**
